beginning-rails-6-blog-chapter-17/config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  resources :users
  resource :session
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
end

beginning-rails-6-blog-chapter-17/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("general.title") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <h1><%= link_to t("general.title"), root_path %></h1>
      <%= language_selector %>

      <div id="user_bar">
        <% if logged_in? %>
          <%= link_to t("articles.new_article"), new_article_path %> |
          <%= link_to t("users.edit_password"), edit_user_path(current_user) %> |
          <%= link_to t("sessions.logout"), logout_path %>
        <% else %>
          <%= link_to t("sessions.login"), login_path %>
        <% end %>
      </div>
    </div>
    <div id="main">
      <%= content_tag :p, notice, class: 'notice' if notice.present? %>
      <%= content_tag :p, alert, class: 'alert' if alert.present? %>
      <%= yield %>
    </div>
    <div id="footer">
      <%= t("general.footer") %>
    </div>
  </body>
</html>