beginning-rails-6-blog-chapter-10/config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles do
    resources :comments
  end
  resources :users
  resource :session
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
end

beginning-rails-6-blog-chapter-10/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :name, :email, :body, presence: true
  validate :article_should_be_published

  after_create :email_article_author

  def article_should_be_published
    errors.add(:article_id, 'is not published yet') if article && !article.published?
  end

  def email_article_author
    puts "We will notify #{article.user.email} in Chapter 12" if article.user
  end
end

beginning-rails-6-blog-chapter-10/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_article, except: :destroy
  before_action :authenticate, only: :destroy

  def create
    @comment = @article.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @article, notice: 'Thanks for your comment' }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @article, notice: 'Unable to add comment' }
        format.js { render :fail_create }
      end
    end
  end

  def destroy
    @article = current_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment deleted' }
      format.js
    end
  end

  private

  def load_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :email, :body)
  end
end

beginning-rails-6-blog-chapter-10/app/helpers/comments_helper.rb
module CommentsHelper
end

beginning-rails-6-blog-chapter-10/app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <h3>
    <%= comment.name %> &lt;<%= comment.email %>&gt; said:
    <% if @article.owned_by? current_user %>
      <span class="actions">
        <%= link_to 'Delete', article_comment_path(article_id: @article, id: comment), confirm: 'Are you sure?', method: :delete, remote: true %>
      </span>
    <% end %>
  </h3>
  <%= comment.body %>
</div>

beginning-rails-6-blog-chapter-10/app/views/comments/_new.html.erb
<%= form_with(model: @article.comments.new, url: article_comments_path(@article)) do |form| %>
  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :email %><br />
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :body %><br />
    <%= form.text_area :body %>
  </div>
  <div class="actions">
    <%= form.submit 'Add' %>
  </div>
<% end %>

beginning-rails-6-blog-chapter-10/app/views/comments/create.js.erb
document.querySelector("#comments").insertAdjacentHTML("beforeend", "<%= escape_javascript render @comment %>");

document.querySelector("#main form").reset();

beginning-rails-6-blog-chapter-10/app/views/comments/destroy.js.erb
var comments = document.querySelector("#comments");
comments.removeChild(document.querySelector("#comment-<%= @comment.id %>"));

beginning-rails-6-blog-chapter-10/app/views/comments/fail_create.js.erb
alert("<%= @comment.errors.full_messages.to_sentence.html_safe %>");

beginning-rails-6-blog-chapter-10/app/views/comments/new.js.erb
document.querySelector("#comments").insertAdjacentHTML("afterend", "<%= escape_javascript render partial: 'new' %>");

var comment_form = document.querySelector("#main form");
comment_form.style.opacity = 0;
setTimeout(function() {
  comment_form.style.transition = 'opacity 1s';
  comment_form.style.opacity = 1;
}, 10);

document.querySelector("#new_comment_link").style.display = 'none';